### ISSUE TITLE
Using Examples Throws An Error

### ISSUE THREAD

**Issue by TheDarkula** [zachomedia/cert-manager-webhook-pdns#46]
I worked through the example in the readme, but after applying the yaml files, the cert-manager pod logs show this:

```
dns.go:88] "cert-manager/challenges/Present: presenting DNS01 challenge for domain" resource_name="test-example-ca-qfkmx-1016260727-3774297136" resource_namespace="default" resource_kind="Challenge" resource_version="v1" dnsName="www.example.com" type="DNS-01" resource_name="test-example-ca-qfkmx-1016260727-3774297136" resource_namespace="default" resource_kind="Challenge" resource_version="v1" domain="www.example.com"

controller.go:167] "cert-manager/challenges: re-queuing item due to error processing" err="failed initializing powerdns provider: failed parsing provider config: error decoding solver config: illegal base64 data at input byte 6" key="default/test-example-ca-qfkmx-1016260727-3774297136
```

**Comment by zachomedia** [comment]
Hello @TheDarkula, if you copied the example as-is, then the `caBundle` value will be invalid (it expects a base64 encoded CA certificate). The example should probably leave that commented-out by default to prevent this.

If you don't need to use a custom CA Cert, then you can just comment out that setting.

**Comment by TheDarkula** [comment]
@zachomedia Ah, I understand, thank you!

Commenting that out did lead to another error, though:
```
1 controller.go:167] "cert-manager/challenges: re-queuing item due to error processing" err="failed loading existing records for _acme-challenge.example.com. in domain example.com.: failed loading zone example.com.: Get \"http://internal.svc.cluster.local:8081/api/v1/servers/localhost/zones/example.com.\": net/http: invalid header field value for \"X-Api-Key\"" key="default/test-example-ca-5mdzv-1016260727-365178633"
```

**Comment by zachomedia** [comment]
I would check that the secret containing the API key is correctly configured.

1. Check the value in the `Secret` object
2. Check the `apiKeySecretRef` points to the right secret and key

**Comment by TheDarkula** [comment]
For the secret, I did `echo "api_key_here" | base64`, and replaced `APIKEY_BASE64` below:
```
apiVersion: v1
kind: Secret
metadata:
  name: pdns-api-key
  namespace: default
type: Opaque
data:
  key: APIKEY_BASE64
```

In the issuer, I have this:
```
              apiKeySecretRef:
                name: pdns-api-key
                namespace: default
                key: key
```
