### ISSUE TITLE
Set http/https proxy via env variables

### ISSUE THREAD

**Issue by bbusioc** [zachomedia/cert-manager-webhook-pdns#47]
Hello,

Is there a was to set the http/s proxy via an environment variable by using the helm chart?  
For some reason, which I can't really understand to reach the power DNS API I have to go through a proxy.  
I manually edited the deployment, added the required HTTP_PROXY, HTTPS_PROXY and NO_PROXY configurations and it worked.  
However, I can't find a way to set environment variables via the helm chart.  

Thanks,
Bogdan

**Comment by bbusioc** [comment]
I fixed it locally on my side by updating like this the env part in the deployment template:
```yaml
          env:
            - name: GROUP_NAME
              value: {{ .Values.groupName | quote }}
            {{- with .Values.http_proxy }}
            - name: HTTP_PROXY
              value: {{ . }}
            {{- end }}
            {{- with .Values.https_proxy }}
            - name: HTTPS_PROXY
              value: {{ . }}
            {{- end }}
            {{- with .Values.no_proxy }}
            - name: NO_PROXY
              value: {{ . }}
            {{- end }}
```
But I think it would be great if this or a better solution could be integrated in your repo.

Thanks,
Bogdan
