### ISSUE TITLE
404 communicating with PowerDNS

### ISSUE THREAD

**Issue by hacknisty** [zachomedia/cert-manager-webhook-pdns#9]
Hi,

I'm trying to setup cert-manager-webhook-pdns using the Helm chart.

The issuer has been defined this way : 
```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: me@me.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
      - dns01:
          webhook:
            groupName: acme.zacharyseguin.ca
            solverName: pdns
            config:
              host: http://pdns:8081
              apiKeySecretRef:
                name: pdns-api-key
                key: key

              # Optional config, shown with default values
              #   all times in seconds
              ttl: 120
              timeout: 30
              propagationTimeout: 120
              pollingInterval: 2
```

The pdns-api-key has been properly setup with the corresponding PDNS api key.

I keep getting this error message in the cert-manager container, and no cert are delivered : 

```
E0120 16:29:59.530988 1 controller.go:163] cert-manager/controller/challenges "msg"="re-queuing item due to error processing" "error"="pdns: unexpected HTTP status code 404 when fetching 'http://pdns:8081/api/v1/'" "key"="default/k8s-example-cert-qwkrh-2391234416-114646716"
```

btw, http://pdns:8081/api/v1/ always return 404 not found in my setup, but querying a server or a zone is working properly.

how can i properly setup this plugin ?

**Comment by zachomedia** [comment]
@vdnclodio Would it be possible to share more about your setup so I can attempt to reproduce the issue?

1. Can you share your PowerDNS deployment + configuration (with any sensitive values removed)?
2. Can you share your `Certificate` manifest?
3. Does the cert-manager-powerdns-webhook pod have any errors in its log?

**Comment by vdnclodio** [comment]
@zachomedia 
1. PowerDNS is deployed on a Debian Buster, version 4.1.6

Configuration: (i only paste the uncommented options, every other options are set to their default value)
```
#################################
# default-soa-name      name to insert in the SOA record if none set in the backend
#
# default-soa-name=a.misconfigured.powerdns.server
default-soa-name=letsencrypt.mydomain


#################################
# include-dir   Include *.conf files from this directory
#
# include-dir=
include-dir=/etc/powerdns/pdns.d

#################################
# launch        Which backends to launch and order to query them in
#
# launch=
launch=

#################################
# local-address Local IP addresses to which we bind
#
# local-address=0.0.0.0
local-address=w.x.y.z


#################################
# webserver     Start a webserver for monitoring (api=yes also enables the HTTP listener)
#
# webserver=no
webserver=yes
api=yes
api-key=myapikey

#################################
# webserver-address     IP Address of webserver/API to listen on
#
# webserver-address=127.0.0.1
webserver-address=w.x.y.z

#################################
# webserver-allow-from  Webserver/API access is only allowed from these subnets
#
# webserver-allow-from=127.0.0.1,::1
webserver-allow-from=0.0.0.0/0

#################################
# webserver-password    Password required for accessing the webserver
#
webserver-password=changeme
```


2. I want to use it to generate Ingress cert : 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-example
  namespace: default
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  rules:
  - host: k8s-example.mydomain
    http:
      paths:
        - path: /apple
          pathType: Prefix
          backend:
            service:
              name: apple-service
              port: 
                number: 5678
  tls:
  - hosts:
    - k8s-example.mydomain
    secretName: k8s-example-cert
```
3. No error in powerdns-webhook pod. Only this : 
```
I0120 16:28:18.629577 1 requestheader_controller.go:169] Starting RequestHeaderAuthRequestController
I0120 16:28:18.629542 1 configmap_cafile_content.go:201] "Starting controller" name="client-ca::kube-system::extension-apiserver-authentication::client-ca-file"
I0120 16:28:18.629605 1 configmap_cafile_content.go:201] "Starting controller" name="client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file"
I0120 16:28:18.629786 1 shared_informer.go:240] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0120 16:28:18.629788 1 shared_informer.go:240] Waiting for caches to sync for RequestHeaderAuthRequestController
I0120 16:28:18.630121 1 secure_serving.go:266] Serving securely on [::]:443
I0120 16:28:18.630223 1 dynamic_serving_content.go:129] "Starting controller" name="serving-cert::/tls/tls.crt::/tls/tls.key"
I0120 16:28:18.629789 1 shared_informer.go:240] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0120 16:28:18.630392 1 tlsconfig.go:240] "Starting DynamicServingCertificateController"
I0120 16:28:18.630893 1 apf_controller.go:299] Starting API Priority and Fairness config controller
I0120 16:28:18.730130 1 shared_informer.go:247] Caches are synced for RequestHeaderAuthRequestController
I0120 16:28:18.730175 1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0120 16:28:18.730589 1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0120 16:28:18.731532 1 apf_controller.go:304] Running API Priority and Fairness config worker
```

**Comment by vdnclodio** [comment]
@zachomedia 

```
    k8s-02.my.me.16658 > letsencrypt.8081: Flags [P.], cksum 0x7f3d (correct), seq 0:185, ack 1, win 507, options [nop,nop,TS val 3975310894 ecr 1822938651], length 185
E...].@.?..._..R_...A.......Cn.d.....=.....
..n.l...GET /api/v1/servers/localhost/zones HTTP/1.1
Host: w.x.y.z:8081
User-Agent: Go-http-client/1.1
X-Api-Key: myapikey
Accept-Encoding: gzip
10:53:34.698422 IP (tos 0x0, ttl 63, id 31692, offset 0, flags [DF], proto TCP (6), length 214)

...

    k8s-02.my.me.44755 > letsencrypt.8081: Flags [P.], cksum 0xac1d (correct), seq 0:162, ack 1, win 507, options [nop,nop,TS val 3974830689 ecr 1822458464], length 162
E...{.@.?..._..R_..........F..l............
...al..`GET /api/v1/ HTTP/1.1
Host: w.x.y.z:8081
User-Agent: Go-http-client/1.1
X-Api-Key: myapikey
Accept-Encoding: gzip
```

any clues on this ?

**Comment by vdnclodio** [comment]
@zachomedia 
Ok so a bit more information about my setup : 
I use a delegated zone for acme challenge : 

same as this : 

https://cert-manager.io/docs/configuration/acme/dns01/#delegated-domains-for-dns01

So if i run the test suite with mydomain.com, i end up with the 404 error on /api/v1/, but if i run the test suite with _acme-challenge.mydomain.com i got this : 

```
--- FAIL: TestRunsSuite (49.39s)
    --- FAIL: TestRunsSuite/Conformance (43.11s)
        --- FAIL: TestRunsSuite/Conformance/Basic (14.03s)
            --- FAIL: TestRunsSuite/Conformance/Basic/PresentRecord (14.03s)
                util.go:59: skipping file "testdata/pdns/README.md" with unrecognised extension
                util.go:68: created fixture "basic-present-record"
                suite.go:37: Calling Present with ChallengeRequest: &v1alpha1.ChallengeRequest{UID:"", Action:"", Type:"", DNSName:"example.com", Key:"123d==", ResourceNamespace:"basic-present-record", ResolvedFQDN:"cert-manager-dns01-tests._acme-challenge.mydomain.com.", ResolvedZone:"_acme-challenge.mydomain.com.", AllowAmbientCredentials:false, Config:(*v1.JSON)(0xc00000e048)}
                suite.go:49: error waiting for DNS record propagation: Could not determine authoritative nameservers for "cert-manager-dns01-tests._acme-challenge.mydomain.com."
        --- FAIL: TestRunsSuite/Conformance/Extended (15.39s)
            --- FAIL: TestRunsSuite/Conformance/Extended/DeletingOneRecordRetainsOthers (15.39s)
                util.go:59: skipping file "testdata/pdns/README.md" with unrecognised extension
                util.go:68: created fixture "extended-supports-multiple-same-domain"
                suite.go:103: error waiting for DNS record propagation: Could not determine authoritative nameservers for "cert-manager-dns01-tests._acme-challenge.mydomain.com."
FAIL
FAIL    github.com/zachomedia/cert-manager-webhook-pdns 49.421s
FAIL
```

is this scenario supported by this webhook ?

**Comment by zachomedia** [comment]
Ah! That might be why, I have not tested this with the delegated domains feature. I'll test it locally and confirm I can reproduce the issue and then figure out how to fix it.

Thanks!

**Comment by zachomedia** [comment]
@vdnclodio Can you try changing your issuer as such:

```yaml

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
# ...
    solvers:
      - dns01:
			 cnameStrategy: Follow
          webhook:
            groupName: acme.zacharyseguin.ca
# ...
```

The `cnameStrategy` seems to be what's needed according to the docs in order to get cert-manager to update the correct zone - and in my limited testing so far seems to fix the issue.
